//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SixShop.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int IdBasket { get; set; }
        public int IdUser { get; set; }
        public int IdItem { get; set; }
        public int IdOrder { get; set; }
        public Nullable<bool> Trueby { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
